-- Read-only metadata verification for HARIS migration 007.
begin read only;
with checks(check_name,passed,details_or_missing) as (
 values
 ('claim_generation_column',exists(select 1 from information_schema.columns where table_schema='public' and table_name='haris_event_outbox' and column_name='claim_generation' and data_type='bigint' and is_nullable='NO' and column_default like '0%'),'haris_event_outbox.claim_generation bigint not null default 0'),
 ('resource_rpc_signatures',to_regprocedure('public.haris_acquire_resource(jsonb)') is not null and to_regprocedure('public.haris_renew_resource(text,text,bigint,integer)') is not null and to_regprocedure('public.haris_release_resource(text,text,bigint)') is not null and (select count(*)=3 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('haris_acquire_resource','haris_renew_resource','haris_release_resource')),'acquire/renew/release exact functions and no overloads'),
 ('outbox_rpc_signatures',to_regprocedure('public.haris_claim_outbox(text,integer,integer)') is not null and to_regprocedure('public.haris_renew_outbox_claim(text,text,bigint,integer)') is not null and to_regprocedure('public.haris_ack_outbox(text,text,bigint)') is not null and to_regprocedure('public.haris_fail_outbox(text,text,text,boolean,bigint)') is not null and (select count(*)=4 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('haris_claim_outbox','haris_renew_outbox_claim','haris_ack_outbox','haris_fail_outbox')),'claim/renew/ack/fail exact functions and no overloads'),
 ('argument_names',(select proargnames=array['p_resource_key','p_incident_id','p_expected_version','p_lease_seconds'] from pg_proc where oid='public.haris_renew_resource(text,text,bigint,integer)'::regprocedure) and (select proargnames=array['p_outbox_id','p_owner','p_claim_generation','p_lease_seconds'] from pg_proc where oid='public.haris_renew_outbox_claim(text,text,bigint,integer)'::regprocedure),'owner/CAS argument names'),
 ('no_legacy_outbox_overloads',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and ((p.proname='haris_ack_outbox' and pg_get_function_identity_arguments(p.oid)='p_outbox_id text, p_owner text') or (p.proname='haris_fail_outbox' and pg_get_function_identity_arguments(p.oid)='p_outbox_id text, p_owner text, p_error_safe text, p_retry boolean'))),'legacy ACK/FAIL absent'),
 ('security_definer',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('haris_acquire_resource','haris_renew_resource','haris_release_resource','haris_claim_outbox','haris_renew_outbox_claim','haris_ack_outbox','haris_fail_outbox') and not p.prosecdef),'all privileged RPCs security definer'),
 ('hardened_search_path',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('haris_acquire_resource','haris_renew_resource','haris_release_resource','haris_claim_outbox','haris_renew_outbox_claim','haris_ack_outbox','haris_fail_outbox') and not coalesce(p.proconfig,'{}') @> array['search_path=public, pg_temp']),'search_path public, pg_temp'),
 ('backend_only_execute',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('haris_acquire_resource','haris_renew_resource','haris_release_resource','haris_claim_outbox','haris_renew_outbox_claim','haris_ack_outbox','haris_fail_outbox') and (has_function_privilege('anon',p.oid,'EXECUTE') or has_function_privilege('authenticated',p.oid,'EXECUTE') or not has_function_privilege('service_role',p.oid,'EXECUTE'))),'service_role only for every migration 007 RPC'),
 ('resource_contract',position('lease_expires_at > v_now' in pg_get_functiondef('public.haris_acquire_resource(jsonb)'::regprocedure))>0 and position('version=p_expected_version' in pg_get_functiondef('public.haris_renew_resource(text,text,bigint,integer)'::regprocedure))>0,'valid lease refusal; expired reclaim; version CAS'),
 ('resource_identity_binding',position('owner_incident_id=p_incident_id' in pg_get_functiondef('public.haris_renew_resource(text,text,bigint,integer)'::regprocedure))>0 and position('owner_incident_id=p_incident_id' in pg_get_functiondef('public.haris_release_resource(text,text,bigint)'::regprocedure))>0,'incident owner and version bound in SQL'),
 ('outbox_contract',position('claim_generation=o.claim_generation+1' in pg_get_functiondef('public.haris_claim_outbox(text,integer,integer)'::regprocedure))>0 and position('claim_generation=p_claim_generation' in pg_get_functiondef('public.haris_renew_outbox_claim(text,text,bigint,integer)'::regprocedure))>0 and position('claim_generation=p_claim_generation' in pg_get_functiondef('public.haris_ack_outbox(text,text,bigint)'::regprocedure))>0 and position('claim_generation=p_claim_generation' in pg_get_functiondef('public.haris_fail_outbox(text,text,text,boolean,bigint)'::regprocedure))>0,'generation advances and binds renew/ack/fail'),
 ('expiry_contract',position('claim_expires_at<now()' in replace(pg_get_functiondef('public.haris_claim_outbox(text,integer,integer)'::regprocedure),' ',''))>0 and position('claim_expires_at>now()' in replace(pg_get_functiondef('public.haris_renew_outbox_claim(text,text,bigint,integer)'::regprocedure),' ',''))>0,'expired reclaim and unexpired renewal')
), result as (select * from checks union all select 'OVERALL',bool_and(passed),'true only when all checks pass' from checks)
select * from result order by case when check_name='OVERALL' then 1 else 0 end,check_name;
rollback;
